### ISSUE TITLE
Fitur Rekap Penjualan

### ISSUE THREAD

**Issue by Eka051** [Eka051/CoffeSharp#12]
Rekap penjualan hasil dari transaksi

**Comment by Edwin811** [comment]
[CoffeSharp.zip](https://github.com/Eka051/CoffeSharp/files/15273052/CoffeSharp.zip)

**Comment by Edwin811** [comment]
[Fitur-Rekap-Penjualan.zip](https://github.com/Eka051/CoffeSharp/files/15285678/Fitur-Rekap-Penjualan.zip)
